### ISSUE TITLE
syslog-gollector and Kafka

### ISSUE THREAD

**Issue by dirtdiver512** [otoolep/syslog-gollector#17]
Trying to use this to take syslog messages and dump in kafka.  I think I have everything running but I can not seem to get syslog-gollector to do anything with logs that are sent to it via UDP 514, the default syslog port.  Rsyslog service is stopped.  I can see the packets getting there but when I check  curl 'localhost:8080/statistics?pretty' I get the below:
 

tcp        0      0 127.0.0.1:514           0.0.0.0:*               LISTEN
udp        0      0 127.0.0.1:514           0.0.0.0:*
udp        0      0 0.0.0.0:1514            0.0.0.0:*

curl 'localhost:8080/statistics?pretty'

{
    "parser": {
        "events.dropped": {
            "count": 0
        },
        "events.parsed": {
            "count": 0
        }
    },
    "tcp": {
        "connections.Active": {
            "count": 0
        },
        "events.bytes.received": {
            "count": 0
        },
        "events.received": {
            "count": 0
        }
    },
    "udp": {
        "events.bytes.received": {
            "count": 0
        },
        "events.received": {
            "count": 0
        }
    }
 
 
 
 
Anyhelp would be great as I am a bit knew to kafka.

**Comment by otoolep** [comment]
Couple of things: 

- show me the diagnostics output, from the diagnostics endpoint. 
- how are you actually sending logs via UDP to the Collector? Have you confirmed the problem is not with your sender? You could read about how to use netcat to listen in UDP mode and dump anything it receives to the terminal, to check the sender.

**Comment by dirtdiver512** [comment]
I have a remote linux box sending to my kafka server syslog via  udp 514. Below are stats from the kafa box

 

sudo ./syslog-gollector -topic="gollector"

[02/20/15 23:21:39] [INFO] syslog server starting on suricata, PID 5032

[02/20/15 23:21:39] [INFO] machine has 4 cores

[02/20/15 23:21:39] [INFO] Admin server: localhost:8080

[02/20/15 23:21:39] [INFO] kafka brokers: localhost:9092

[02/20/15 23:21:39] [INFO] kafka topic: gollector

[02/20/15 23:21:39] [INFO] kafka batch size: 10

[02/20/15 23:21:39] [INFO] kafka buffer time: 1000ms

[02/20/15 23:21:39] [INFO] kafka buffer bytes: 524288

[02/20/15 23:21:39] [INFO] parsing enabled: true

[02/20/15 23:21:39] [INFO] channel buffering capacity: 0

[02/20/15 23:21:39] [INFO] Admin server started

[02/20/15 23:21:39] [INFO] kafka producer created

[02/20/15 23:21:39] [INFO] connected to kafka at localhost:9092

[02/20/15 23:21:39] [INFO] listening on localhost:514 for TCP connections

[02/20/15 23:21:39] [INFO] listening on localhost:514 for UDP packets

 

 

 

 

curl 'localhost:8080/diagnostics?pretty'

{

    "started": "2015-02-20 23:21:39.341678484 -0600 CST",

    "uptime": "5m45.742057605s"

**Comment by dirtdiver512** [comment]
Ok found out my main issue….now gollector is getting the logs but I do not see them going into kafka…

I did test kafka with the cli producer and consumer and I can type in the producer and see it kicked out the consumer

 

 

 

curl 'localhost:8080/statistics?pretty'

{

    "parser": {

        "events.dropped": {

            "count": 24

        },

        "events.parsed": {

            "count": 0

        }

    },

    "tcp": {

        "connections.Active": {

            "count": 0

        },

        "events.bytes.received": {

            "count": 0

        },

        "events.received": {

            "count": 0

        }

    },

    "udp": {

        "events.bytes.received": {

            "count": 6144

        },

        "events.received": {

            "count": 24

        }

    }

**Comment by otoolep** [comment]
Yeah, those logs show the Collector starting up OK, but you should instead start `netcat` on the same box and have it listen to port 514 UDP. That is how I would confirm that UDP traffic is making it to the box.

`netcat -klu 0.0.0.0`

**Comment by otoolep** [comment]
if they are being dropped, they do not match the required format for parsing. Please ensure the log lines are compliant with that described in the README. It describes how to configure syslog senders to encode the lines in the correct format.

If your lines are in the correct format, but still getting dropped, please re-open this issue. Alternatively disable parsing.

**Comment by dirtdiver512** [comment]
FYI I found two issues.  One, by default it listens to 127.0.0.1, I had to change it to 0.0.0.0

Two, on the remote system, I had rsyslog configurured as *.* @@x.x.x.x

I didn’t realize that the @@ was for TCP and @ as for UDP.  I realized it while looking at the tcpdump that there were syn numbers, which should not be for UDP.   

 

Working now so thanks!
